# Generated by Django 3.1.2 on 2020-11-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201122_0618'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
