# Generated by Django 3.1.2 on 2020-12-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20201201_0530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
